// =============================================================================
// BETTHAT — Privacy Policy
// =============================================================================

import { View, Text, ScrollView, Pressable } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import Svg, { Path } from 'react-native-svg';
import { HG, FONT } from '@/lib/holygrail';

export default function PrivacyScreen() {
  const router = useRouter();

  return (
    <SafeAreaView edges={['top']} style={{ flex: 1, backgroundColor: HG.jet }}>
      <View style={{ flexDirection: 'row', alignItems: 'center', paddingHorizontal: 18, height: 54, gap: 14 }}>
        <Pressable onPress={() => router.back()} hitSlop={12}>
          <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke={HG.ink2} strokeWidth={1.6} strokeLinecap="round" strokeLinejoin="round">
            <Path d="m15 18-6-6 6-6" />
          </Svg>
        </Pressable>
        <Text style={{ fontFamily: FONT.serif, fontSize: 24, color: HG.ink, letterSpacing: -0.3 }}>Privacy Policy</Text>
      </View>

      <ScrollView contentContainerStyle={{ paddingHorizontal: 22, paddingBottom: 60, gap: 22 }}>
        <Text style={{ fontFamily: FONT.monoMedium, fontSize: 10, color: HG.muted, letterSpacing: 1.4, textTransform: 'uppercase', marginTop: 8 }}>
          Last updated: January 1, 2025 · Version 1.0
        </Text>

        <Section title="1. Information We Collect">
          We collect information you provide directly (name, email, date of birth, state of residence), information generated by your use of the platform (matchup history, transaction records, gameplay data), and device information (device ID, IP address, operating system) for fraud prevention and compliance.
        </Section>

        <Section title="2. How We Use Your Information">
          We use your information to operate the platform, verify your identity and age, process payments, detect fraud, provide customer support, comply with legal obligations (including AML/KYC requirements), and improve our services.
        </Section>

        <Section title="3. Identity Verification (KYC)">
          As a real-money gaming platform, we are required to verify the identity of users who reach certain transaction thresholds. We use a third-party KYC provider. Your ID documents are not stored by BETTHAT directly.
        </Section>

        <Section title="4. Payment Information">
          Payment processing is handled by Stripe. BETTHAT does not store your full credit card or bank account numbers. Stripe's privacy policy governs their handling of your payment data.
        </Section>

        <Section title="5. Data Sharing">
          We do not sell your personal data. We share data with service providers who assist us in operating the platform (payment processors, KYC providers, cloud hosting), with law enforcement when required by law, and with regulatory bodies as required for gaming compliance.
        </Section>

        <Section title="6. Data Retention">
          We retain account information for the duration of your account plus 7 years for regulatory compliance. Transaction records are retained for 7 years. You may request deletion of non-regulatory data by contacting support.
        </Section>

        <Section title="7. Security">
          We use industry-standard encryption and security practices to protect your data. All data is transmitted over HTTPS. Database access is restricted by role-level security policies.
        </Section>

        <Section title="8. Your Rights">
          Depending on your state of residence, you may have the right to access, correct, or delete your personal data. Contact us at privacy@betthat.com to exercise these rights.
        </Section>

        <Section title="9. Children's Privacy">
          BETTHAT is not intended for users under 18. We do not knowingly collect information from minors. If we discover we have collected data from a minor, we will delete it immediately.
        </Section>

        <Section title="10. Changes to This Policy">
          We may update this Privacy Policy. We will notify you of material changes via in-app notification. Continued use of BETTHAT after changes constitutes acceptance.
        </Section>

        <Text style={{ fontFamily: FONT.sans, fontSize: 12, color: HG.muted2, textAlign: 'center', marginTop: 16, lineHeight: 18 }}>
          Questions? Contact privacy@betthat.com
        </Text>
      </ScrollView>
    </SafeAreaView>
  );
}

function Section({ title, children }: { title: string; children: string }) {
  return (
    <View style={{ gap: 8 }}>
      <Text style={{ fontFamily: FONT.sansBold, fontSize: 14, color: HG.ink, letterSpacing: 0.2 }}>{title}</Text>
      <Text style={{ fontFamily: FONT.sans, fontSize: 14, color: HG.ink2, lineHeight: 22 }}>{children}</Text>
    </View>
  );
}
